[tools]
go = "1.26"
golangci-lint = "2.12.2"
node = "26"
pnpm = "12"

[env]
CGO_ENABLED = "0"

[tasks.default]
run = [
    { task = "dev" },
]

# Local environment management

[tasks.dev]
depends = [ "backend:build" ]
run = "docker compose up -d --wait"

[tasks."dev:reload"]
depends = [ "backend:build" ]
run = "docker compose restart teamcity-monitor-backend"

[tasks."dev:down"]
run = "docker compose down"

[tasks."dev:ps"]
run = "docker compose ps"

[tasks."dev:logs"]
run = "docker compose logs -f"

# Builds

[tasks.build]
run = [
    { task = "backend:build" },
    { task = "web:build" },
]

[tasks."backend:modules"]
dir = "backend"
run = "go mod tidy"

[tasks."backend:build"]
dir = "backend"
depends = [ "backend:modules" ]
run = """go build \
-trimpath -v \
--gcflags 'all=-N -l' \
-o ./bin/teamcity-monitor ./cmd/teamcity-monitor
"""

[tasks."web:modules"]
dir = "web"
run = "pnpm install --frozen-lockfile"

[tasks."web:build"]
dir = "web"
depends = [ "web:modules" ]
run = "pnpm run build"

# Checks

[tasks.check]
run = [
    { task = "test" },
    { task = "lint" },
]

# Tests

[tasks.test]
run = [
    { task = "backend:test" },
    { task = "web:test" },
]

[tasks."backend:test"]
dir = "backend"
run = "go test ./..."

[tasks."web:test"]
dir = "web"
run = "pnpm run test"

# Linting

[tasks.lint]
run = [
    { task = "backend:lint" },
    { task = "web:lint" },
]

[tasks."backend:lint"]
dir = "backend"
run = [ "golangci-lint run" ]

[tasks."web:lint"]
dir = "web"
run = [ "pnpm run lint" ]
